name: lEver
main: co.lotc.lever.Lever
version: ${project.version}
author: Sporadic
depend: [ArcheCore]
softdepend:  [Omniscience]
api-version: 1.13

commands:
  list:
    description: list online players
    permission: lever.list
  near:
    description: Show all the players nearby you
    permission: lever.near
  warp:
    description: Teleport to a pre-defined location
    permission: lever.warp
  invsearch:
    description: Request to search another player's inventory
    permission: lever.invsearch
  roll:
    description: Roll an amount of dice
    permission: lever.roll
  sneak:
    description: toggle sneak
    permission: lever.sneak
  walk:
    description: Sets your speed to walking
    permission: lever.walk
  fly:
    description: toggle flight
    permission: lever.fly
  speed:
    description: Adjust walking or flying speed
    permission: lever.speed
  i:
    description: Spawn an item
    permission: lever.item
    aliases: [item]
  changematerial:
    description: Change the material of an item
    permission: lever.item
  spectate:
    description: Spectator mode toggle command
    permission: lever.spectate
  vanish:
    description: Vanish mode toggle command
    permission: lever.vanish
    aliases: [v]
  back:
    description: Return from the last registered teleportation
    permission: lever.back
  viewdistance:
    description: Manipulate radius of chunks loaded around players
    permission: lever.viewdistance
  mobproximity:
    description: Checks for proximity of mobs
    permission: lever.mobproximity
  horsestats:
    description: Check speed of the horse you are riding
    permission: lever.horsestats
  trash:
    description: open an inventory to dispose of unwanted items
    permission: lever.trash
  showitem:
    description: show item in hand to player
    permission: lever.showitem
  impersonate:
    description: impersonate another player
    permission: lever.impersonate
permissions:
  lever.vanish.cansee:
    description: Can see vanished players as normal
  lever.vanish.persist:
    description: vanish persists through logouts and restarts
  lever.vanish.elevated:
    description: Vanish that can't be seen except by others with this node AND lever.vanish.cansee
  lever.vanish.admin:
    description: Vanish that can never be seen
  lever.fly.persist:  
    description: fly persists through logouts and restarts
  lever.warpsign:
    description: Allows creation of warp signs
  lever.list.names:
    description: Prints player names in the /list command
