name: lEver
main: co.lotc.lever.Lever
version: ${project.version}
author: Sporadic
depend: [ArcheCore]
softdepend:  [Omniscience]
api-version: 1.13

commands:
  list:
    description: List online players
    permission: lever.list
  near:
    description: Show all the players nearby
    permission: lever.near
  warp:
    description: Teleport to a pre-defined location
    permission: lever.warp
  invsearch:
    description: Request to search another player's inventory
    permission: lever.invsearch
  roll:
    description: Roll an amount of dice
    permission: lever.roll
  sneak:
    description: Toggle sneak
    permission: lever.sneak
  walk:
    description: Sets your speed to walking
    permission: lever.walk
  fly:
    description: Toggle flight
    permission: lever.fly
  i:
    description: Spawn an item
    permission: lever.item
    aliases: [item]
  changematerial:
    description: Change the material of an item
    permission: lever.item
  spectate:
    description: Spectator mode toggle command
    permission: lever.spectate
  vanish:
    description: Vanish mode toggle command
    permission: lever.vanish
    aliases: [v]
  back:
    description: Return from the last registered teleportation
    permission: lever.back
  viewdistance:
    description: Manipulate radius of chunks loaded around players
    permission: lever.viewdistance
  mobproximity:
    description: Checks for proximity of mobs
    permission: lever.mobproximity
  horsestats:
    description: Check the speed of the horse you're riding
    permission: lever.horsestats
  trash:
    description: Open an inventory to dispose of unwanted items
    permission: lever.trash
  showitem:
    description: Show held item to another player
    permission: lever.showitem
  impersonate:
    description: Impersonate another player
    permission: lever.impersonate
  countdown:
    description: Start a PvP countdown
    permission: lever.countdown
  emote:
    description: Broadcast an emote to nearby players
    permission: lever.emote
permissions:
  lever.vanish.cansee:
    description: Can see vanished players as normal
  lever.vanish.persist:
    description: Vanish persists through logouts and restarts
  lever.vanish.elevated:
    description: Vanish that can't be seen except by others with this node AND lever.vanish.cansee
  lever.vanish.admin:
    description: Vanish that can never be seen
  lever.fly.persist:  
    description: Fly persists through logouts and restarts
  lever.warpsign:
    description: Allows creation of warp signs
  lever.list.names:
    description: Prints player names in the /list command
  lever.countdown.radius:
    description: Allows the broadcast radius of countdowns to be set
